(for i in `seq 1 50`;   
do python weightCycles.py phase1-processed/1/${i}.in results/${i}.cyc; done)
(for i in `seq 51 100`;   
do python weightCycles.py phase1-processed/2/${i}.in results/${i}.cyc; done)
(for i in `seq 101 150`;   
do python weightCycles.py phase1-processed/3/${i}.in results/${i}.cyc; done)
(for i in `seq 151 200`;   
do python weightCycles.py phase1-processed/4/${i}.in results/${i}.cyc; done)
(for i in `seq 201 250`;   
do python weightCycles.py phase1-processed/5/${i}.in results/${i}.cyc; done)
(for i in `seq 251 300`;   
do python weightCycles.py phase1-processed/6/${i}.in results/${i}.cyc; done)
(for i in `seq 301 350`;   
do python weightCycles.py phase1-processed/7/${i}.in results/${i}.cyc; done)
(for i in `seq 351 400`;   
do python weightCycles.py phase1-processed/8/${i}.in results/${i}.cyc; done)
(for i in `seq 401 450`;   
do python weightCycles.py phase1-processed/9/${i}.in results/${i}.cyc; done)
(for i in `seq 451 492`;   
do python weightCycles.py phase1-processed/10/${i}.in results/${i}.cyc; done)